### ISSUE TITLE
单调栈-1.4板子题-1.4.2代码实现有错误

### ISSUE THREAD

**Issue by jc1144096387** [muyids/leetcode#1]
感觉大佬的算法教程。
我在学习单调栈的时候，发现1.4板子题-1.4.2代码实现有错误。运行结果和样例的结果不一致
void sumSubarrayMins(vector<int> &A) {
    int n = A.size();
    vector<int> lmin(n, -1);
    vector<int> rmin(n, -1);
    stack<int> stk; // 单调递增栈
    for (int i = 0; i < A.size(); i++) {
        while (stk.size() && A[i] <= A[stk.top()]) {
            rmin[stk.top()] = A[i];
            stk.pop();
            if (stk.size()) lmin[i] = A[stk.top()];
        }
        stk.push(i);
    }
}

此处的if (stk.size()) lmin[i] = A[stk.top()];应该放在while循环外面，即

void sumSubarrayMins(vector<int> &A) {
    int n = A.size();
    vector<int> lmin(n, -1);
    vector<int> rmin(n, -1);
    stack<int> stk; // 单调递增栈
    for (int i = 0; i < A.size(); i++) {
        while (stk.size() && A[i] <= A[stk.top()]) {
            rmin[stk.top()] = A[i];
            stk.pop();
        }
        if (stk.size()) lmin[i] = A[stk.top()];
        stk.push(i);
    }
}

**Comment by muyids** [comment]
感谢勘误，已经fix

CPP
```cpp []
void sumSubarrayMins(vector<int> &A) {
    int n = A.size();
    vector<int> lmin(n, -1); // 左边第一个更小的元素
    vector<int> rmin(n, -1); // 右边第一个更小的元素
    stack<int> stk; // 单调递增栈
    for (int i = 0; i < A.size(); i++) {
        while (stk.size() && A[i] <= A[stk.top()]) {
            rmin[stk.top()] = A[i];
            stk.pop();
        }
        if (stk.size()) lmin[i] = A[stk.top()];
        stk.push(i);
    }
}
```
JAVA
```java []
public void sumSubarrayMins(int[] nums) {
    int n = nums.length;

    int[] lmin = new int[n];
    int[] rmin = new int[n];
    Arrays.fill(lmin, -1);
    Arrays.fill(rmin, -1);
    Deque<Integer> stk = new ArrayDeque<>();
    for (int i = 0; i < n; i++) {
        while (!stk.isEmpty() && nums[i] <= nums[stk.getLast()]) {
            rmin[stk.getLast()] = nums[i];
            stk.pollLast();
        }
        if (!stk.isEmpty()) lmin[i] = nums[stk.getLast()];
        stk.addLast(i);
    }
}
```
时间复杂度`O(N)`，空间复杂度`O(N)`
